/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class haxebridge_Bridge */

#ifndef _Included_haxebridge_Bridge
#define _Included_haxebridge_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     haxebridge_Bridge
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_haxebridge_Bridge_sendMessage
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     haxebridge_Bridge
 * Method:    initNativeListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_haxebridge_Bridge_initNativeListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
